services:
  dev_postgres:
    image: postgres:latest
    container_name: dev_postgres
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: ".env"

volumes:
  dev_postgres_data:
